django_official_mywebsite/django_official_mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth import views
from polls.views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('',TemplateView.as_view(template_name='index.html'),name='home'),

    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/signup/', signup, name='signup')
]

django_official_mywebsite/polls/urls.py
from django.urls import path,include
from . import views

app_name='polls'

urlpatterns=[

    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
    path('add/question/',views.AddQuestion,name='add_question'),
    path('add/choice/<int:question_id>', views.AddChoice, name='add_choice'),
    path('add/choice/', views.AddChoice, name='add_choice'),
    path('search/',views.SearchView.as_view(),name='search'),
    path('contact/',views.contact,name='contact'),
    path('edit/question/<int:question_id>', views.EditQuestion, name='edit_question'),
    path('edit/choice/<int:choice_id>', views.EditChoice,name='edit_choice'),



]





# urlpatterns=[
#     path('',views.index,name='index'),
#     path('<int:question_id>/',views.detail,name='detail'),
#     path('<int:question_id>/results/',views.results,name='results'),
#     path('<int:question_id>/vote/',views.vote,name='vote'),
# ]

django_official_mywebsite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date= models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()- datetime.timedelta(days=1)

class Choice(models.Model):
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text= models.CharField('choice text',max_length=200)
    votes= models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_official_mywebsite/polls/forms.py
from django import forms
from .models import Question,Choice
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class QuestionForm(forms.Form):
     question_text= forms.CharField(label='Question Text', max_length=200)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(label="send me a copy of response",required=False)

# class QuestionForm(forms.ModelForm):
#     class Meta:
#         model= Question
#         fields= ('question_text',)
class ChoiceForm(forms.ModelForm):
    class Meta:
        model= Choice
        fields= ('question','choice_text')

class SignUpForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2' )

"Password1 and password2 are defined in UserCreationForm whereas Password is defined in User"


# class SignUpForm(forms.ModelForm):
#
#     password=forms.CharField(widget=forms.PasswordInput)
#
#     class Meta:
#         model= User
#         fields=['username','email','password']



# class SignUpForm(forms.Form):
#     username = forms.CharField(
#         required = True,
#         label = 'Username',
#         max_length = 32
#     )
#     email = forms.CharField(
#         required = True,
#         label = 'Email',
#         max_length = 32,
#     )
#     password = forms.CharField(
#         required = True,
#         label = 'Password',
#         max_length = 32,
#         widget = forms.PasswordInput()
#     )

django_official_mywebsite/polls/views.py
from .models import Question,Choice
from django.views import generic
from django.urls import reverse,reverse_lazy
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect
from .forms import QuestionForm,ContactForm,ChoiceForm,SignUpForm
from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms


from django.core.mail import send_mail

class IndexView(generic.ListView):
    template_name='polls/index.html'
    context_object_name='latest_qlist'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:10]


class DetailView(generic.DetailView):
    model=Question
    template_name='polls/detail.html'

class ResultsView(generic.DetailView):
    model=Question
    template_name='polls/results.html'

class SearchView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_qlist'

    def get_queryset(self):

        if(self.request.method=="GET"):
            search_term=self.request.GET.get('search_key')
            return Question.objects.filter(question_text__regex=r'%s'%search_term)
        else:
            return redirect(reverse('polls:index'))



def vote(request, question_id):

    question=get_object_or_404(Question,pk=question_id)

    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])

    except (KeyError,choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message': "Please select a valid choice"
        })

    else:
        selected_choice.votes+=1;
        selected_choice.save();


        return redirect(reverse('polls:results', args=(question_id,)))
        # return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))

#Without using model form

def AddQuestion(request):

    if request.method=="POST":
        form= QuestionForm(request.POST)

        if form.is_valid():
            question=Question()
            question.question_text= form.cleaned_data['question_text']
            question.pub_date=timezone.now()
            question.save()
            return redirect(reverse('polls:index'))

    else:
        form=QuestionForm()

    return render(request,'polls/add_form.html',{'form_type': 'question','form':form,'action':'add'})

def EditQuestion(request,question_id):

    question=get_object_or_404(Question,pk=question_id)

    if request.method=='POST':
        form=QuestionForm(request.POST)

        if form.is_valid():
            question.question_text= form.cleaned_data['question_text']
            question.save()
            return redirect(reverse('polls:detail',args=(question.id,)))

    else:
            # form=QuestionForm({'question_text':question.question_text})
            form = QuestionForm(initial={'question_text': question.question_text})
    return render(request,'polls/add_form.html',{'form':form,'action':'edit','form_type': 'question'})


'''

# using model form

def AddQuestion(request):

    if request.method=='POST':
        form=QuestionForm(request.POST)

        if form.is_valid():
            question=form.save(commit=False)
            question.pub_date=timezone.now()
            question.save()
            return redirect(reverse('polls:detail',args=(question.id,)))

    else:
            form=QuestionForm()
    return render(request,'polls/add_form.html',{'form':form,'form_type': 'question','action':'add'})

def EditQuestion(request,question_id):

    question=get_object_or_404(Question,pk=question_id)

    if request.method=='POST':
        form=QuestionForm(request.POST, instance=question)

        if form.is_valid():
            question=form.save(commit=False)
            question.save()
            return redirect(reverse('polls:detail',args=(question.id,)))

    else:
            form=QuestionForm(instance=question)
    return render(request,'polls/add_form.html',{'form':form,'action':'edit','form_type': 'question'})
'''

def AddChoice(request,question_id=0):
    if(question_id):
        question=get_object_or_404(Question,pk=question_id)
    else:
        question=None

    if request.method=="POST":
        form= ChoiceForm(request.POST)

        if form.is_valid():
            choice=form.save()
            return redirect(reverse('polls:detail',args=(choice.question.id,)))

    else:
        form=ChoiceForm(initial={'question':question})

    return render(request,'polls/add_form.html',{'form_type': 'choice','form':form,'action':'add'})

def EditChoice(request,choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)

    if request.method == 'POST':
        form = ChoiceForm(request.POST, instance=choice)

        if form.is_valid():
            choice = form.save()
            return redirect(reverse('polls:detail', args=(choice.question.id,)))

    else:
        form = ChoiceForm(instance=choice)
    return render(request, 'polls/add_form.html', {'form': form, 'action': 'edit', 'form_type': 'choice'})



def contact(request):
    if request.method=="POST":
        form= ContactForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            superusers_emails = User.objects.filter(is_superuser=True).values_list('email')
            recipients =list(superusers_emails[0])
            if cc_myself:
                recipients.append(sender)

            #send_mail(subject,message,sender,recipients)


            return redirect(reverse('polls:index'))

    else:
        form=ContactForm()

    return render(request,'polls/form.html',{'form':form})





#Using CreateFormView Signup With Extra Fields without generic view

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            print(form.cleaned_data)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)

            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})



'''
# Using CreateFormView Signup With Extra Fields with generic view

class signup(generic.CreateView):
    form_class=SignUpForm
    success_url=reverse_lazy('home')
    template_name= 'registration/signup.html'


'''


#Extra field without model form or usercreateview ie from the basics
'''
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        print(form)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email = userObj['email']
            password = userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('home')
            else:

                ####################ask how to return this error back to form#############
                form.fields['email'].errors=['Email address already exists']

                raise forms.ValidationError('Looks like a username with that email or password already exists')


    else:
        form = SignUpForm()

    return render(request, 'registration/signup.html', {'form': form})


'''



#Using Model Forms with Extra Fields without createformview
"""
def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():

            user=form.save(commit=False)
            print(form.cleaned_data)

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


"""



#Signup Without Extra Fields using createformview

"""

def signup(request):
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        
        if form.is_valid():
            form.save()

            print(form.cleaned_data)
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password1')
            user= authenticate(username=username,password=password)

            login(request,user)
            return redirect('home')



    else:
        form= UserCreationForm()
    return render(request,'registration/signup.html',{'form':form})

"""



'''
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question
from django.template import loader
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse

def index(request):
    latest_qlist= Question.objects.order_by('-pub_date')[:5]

    return render(request,'polls/index.html',{'latest_qlist':latest_qlist})

    # template=loader.get_template('polls/index.html')
    #
    # return HttpResponse(template.render({'latest_qlist':latest_qlist},request))

def detail(request, question_id):

    question= get_object_or_404(Question,pk=question_id)

    return render(request,'polls/detail.html',{'question':question})


    # try:
    #     question = Question.objects.get(pk=question_id)

django_official_mywebsite/polls/templates/polls/add_form.html
{% extends 'polls/base.html' %}

{% block title %}New {{ form_type }}{% endblock %}

{% block content %}

<p>Here you can {{ action }} a {{ form_type }}</p>

<form action="" method="post">
{% csrf_token %}
    {% include 'polls/form_template.html' %}

{#     {{ form.question_text.label_tag }}#}
{#    <input type="text" name="question_text" maxlength="200" required id="id_question_text"#}
{#           {% if form.question_text.value %}value="{{ form.question_text.value }}"{% endif %}#}
{#           placeholder="Eg. How is the josh?"#}
{#           >#}


    <input type="submit" value="{{ action }} {{ form_type }}">
</form>

{% endblock %}

django_official_mywebsite/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
    <title>{% block title %}Polling App{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>

 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand " href="{% url 'polls:index' %}">
        Polling App
      </a>

        <ul class="nav navbar-nav pt-3">

            <li class="nav-item"> <a class="nav-link " href="{% url 'polls:index' %}">Questions</a></li>
            <li class="nav-item">
                <form class="navbar-form form-inline" role="search" method="GET" action="{% url 'polls:search' %}">
                     <input class="form-control" type="text" name="search_key" placeholder="Search For a Question">
                    <input class="btn btn-outline-success" type="submit" value="Search">
                </form>
            </li>
        </ul>


        <div class="d-block d-flex flex-row ml-auto">
            <ul class="nav navbar-nav">
                <li class="nav-item">  <a href="{% url 'polls:add_question' %}" class="nav-link" >Add Question</a></li>
                <li class="nav-item">  <a href="{% url 'polls:add_choice' %}" class="nav-link" >Add Choice</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'polls:contact' %}">Contact Us</a></li>
            </ul>
        </div>
    </nav>



{% block content %}
{% endblock %}

</body>
</html>

django_official_mywebsite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}Details{% endblock %}

{% block content %}


<h1>{{ question.question_text }}</h1>
    <a href="{% url 'polls:edit_question' question.id %}">Edit</a>
    <a href="{% url 'polls:add_choice' question.id %}">add choice</a>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <a href="{% url 'polls:edit_choice' choice.id %}">edit</a>
        </li>
        {% endfor %}
    </ul>
    <input type="submit" value="vote">
</form>



{% endblock %}

django_official_mywebsite/polls/templates/polls/form.html
{% extends 'polls/base.html' %}

{% block title %}Contact us{% endblock %}

{% block content %}

<p>Drop us a word</p>

<form action="" method="post">
{% csrf_token %}

    {#    {{ form.as_p }}#}

{#    <p><label for="id_subject">Subject:</label>#}
{#    <input id="id_subject" type="text" name="subject" maxlength="100" required></p>#}
{#<p><label for="id_message">Message:</label>#}
{#    <textarea name="message" id="id_message" required></textarea></p>#}
{#<p><label for="id_sender">Sender:</label>#}
{#    <input type="email" name="sender" id="id_sender" required></p>#}
{#<p><label for="id_cc_myself">Cc myself:</label>#}
{#    <input type="checkbox" name="cc_myself" id="id_cc_myself"></p>#}
{#    <input type="submit" value="send">#}
{#</form>#}

{{ form.non_field_errors }}
<div class="fieldWrapper">
    {{ form.subject.errors }}
    {{ form.subject.label_tag }}
    {{ form.subject }}
</div>
<div class="fieldWrapper">
    {{ form.message.errors }}
    <label for="{{ form.message.id_for_label }}">Your message:</label>
    {{ form.message }}
</div>
<div class="fieldWrapper">
    {{ form.sender.errors }}
    <label for="{{ form.sender.id_for_label }}">Your email address:</label>
    {{ form.sender }}
</div>
<div class="fieldWrapper">
    {{ form.cc_myself.errors }}
    <label for="{{ form.cc_myself.id_for_label }}">{{ form.cc_myself.label }}</label>
    {{ form.cc_myself }}
</div>

<input type="submit" value="send">

{% endblock %}

django_official_mywebsite/polls/templates/polls/form_template.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

django_official_mywebsite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}



{% block content %}


{% if latest_qlist %}
    <ul>
        {% for question in latest_qlist %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No question available</p>
{% endif %}


{% endblock %}

django_official_mywebsite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}Results{% endblock %}

{% block content %}


<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}--{{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>

{% endblock %}