TheNewBostonDjango/TheNewBostonDjango/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TheNewBostonDjango/music/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),

    # /music/71/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('register/', views.UserFormView.as_view(), name='register'),


    # #/music/<album-id>/favourite
    # path('<int:album_id>/favourite/', views.favourite, name='favourite')

    #music/album/add
    path('album/add/',views.AlbumCreate.as_view(), name='add'),

    #music/album/2
    path('album/<int:pk>/',views.AlbumUpdate.as_view(), name='update'),

    # music/album/2/delete
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='delete'),

]

TheNewBostonDjango/music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    artist= models.CharField(max_length=20)
    album_title=models.CharField(max_length=40)
    genre =models.CharField(max_length=10)
    album_logo= models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title+ "-" + self.artist + "-"+ self.genre

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title= models.CharField(max_length=250)
    is_favourite=models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

TheNewBostonDjango/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model= User
        fields=['username','email','password']

TheNewBostonDjango/music/views.py
from django.views import generic
from .models import Album
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy

class IndexView(generic.ListView):
    template_name='music/index.html'
    context_object_name='all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model= Album
    template_name='music/detail.html'


class AlbumCreate(CreateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url=reverse_lazy('music:index')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class UserFormView(View):
    form_class=UserForm
    template_name='music/registration_form.html'

    #display blank form
    def get(self,request):
        form=self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user=form.save(commit=False)

            #clean/normalise data
            username= form.cleaned_data['username']
            password= form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return User object if credentials are correct

            user=authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})


'''from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, Http404
from .models import Album,Song
from django.template import loader
# Create your views here.

def index(request):
    all_albums=Album.objects.all()
    template= loader.get_template('music/index.html')
    context={'all_albums': all_albums}

    return HttpResponse(template.render(context, request))
    # return render(request, 'music/index.html', context)

    # Avoid writing html inside python files
    # html = ''
    # for album in all_albums:
    #     url='/music/{}/'.format(album.id)
    #     html+= '<a href={}>{}</a><br>'.format(url,album.album_title)
    # return HttpResponse('<h1>This is a music app Homepage. List of all albums</h1>'+ html)
    #

    # other way of rendering the template##################




def detail(request, album_id):

    try:
        album= Album.objects.get(id=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")

    return render(request, 'music/detail.html', {'album' : album} )



    #############Another method for 404 display#
    # album=get_object_or_404(Album,id=album_id)
    # return render(request,'music/detail.html', {'album':album})

    #return HttpResponse('<h2>deatils for album id {} is available on this page</h2>'.format(album_id))

def favourite(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album':album,
            'error_message': "No valid song selected"
        })
    else:
        selected_song.is_favourite=True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})
'''

TheNewBostonDjango/music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %}Album detail{% endblock %}

{% block music_block %}


    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'music/form-template.html' %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </form>



{% endblock %}

TheNewBostonDjango/music/templates/music/base.html
<!DOCTYPE HTML>
<html>
<head>
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>{% block title %}Music{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand " href="{% url 'music:index' %}">
        Music Album
      </a>
        <ul class="nav navbar-nav pt-3">

            <li class="nav-item"> <a class="nav-link " href="#">Albums</a></li>
            <li class="nav-item"> <a class="nav-link " href="#">Song</a></li>
            <li class="nav-item">
                <form class="navbar-form form-inline" role="search" method="get" action="#">
                     <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="q" value="">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </li>
        </ul>


        <div class="d-block d-flex flex-row ml-auto">
            <ul class="nav navbar-nav">
                <li class="nav-item">  <a href="{% url 'music:add' %}" class="nav-link" >Add</a></li>
                 <li class="nav-item"> <a class="nav-link " href="#">Logout</a></li>
            </ul>
        </div>
    </nav>

{% block music_block %}
{% endblock %}


</body>
</html>

TheNewBostonDjango/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <span>{{ field.errors }}</span>
    </div>
    {{ field.label_tag }}
    {{ field }}
{% endfor %}

TheNewBostonDjango/music/templates/music/index.html
<!-- loads the path to static file> -->
{% extends 'music/base.html' %}

{% block music_block %}

{% if all_albums %}
    <h3>Here are all my albums</h3>
    <ul>
        {% for album in all_albums %}
        <li>
            <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
        </li>
            <a href="{% url 'music:delete' album.id %}" class="btn">delete</a>
            <a href="{% url 'music:update' album.id %}" class="btn">edit</a>
        {% endfor %}
    </ul>

{% else %}
    <h3> Please add some albums</h3>
{% endif %}

{% endblock %}

TheNewBostonDjango/music/templates/music/registration_form.html
{% extends 'music/base.html' %}

{% block title %}Register{% endblock %}

{% block music_block %}


    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'music/form-template.html' %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </form>



{% endblock %}